# Generated by Django 4.1.4 on 2023-01-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room <built-in function id>', max_length=50, unique=True),
        ),
    ]
